from pathlib import Path
import base64, hashlib, json, subprocess

ART = 'docs/design/dali/studies/six-bamboo-c-green-approved.svg'
RUNTIME = 'web/public/tiles/dali/approved/Sou6.svg'
DIRECTION = 'The Impossible Reflection — Green C'
ORIGINAL = '233988575615df0c4a4247b0f3ca05b67aad37a0135274b21e281fc79c280da6'
RASTER = 'b71742d237ae7bce1595ec0baecac878c666f27949a2ccceb1b696e4ee6676ea'
SVG_HASH = '174285598c4569561efa7f0832f3b6c34fd52e653ffca6bba5dc3e941c237762'
sha = lambda data: hashlib.sha256(data).hexdigest()
read = lambda p: Path(p).read_text(encoding='utf-8')
def write(p, text):
    Path(p).parent.mkdir(parents=True, exist_ok=True)
    Path(p).write_text(text, encoding='utf-8')
def replace_once(text, before, after):
    assert text.count(before) == 1, f'Expected one anchor: {before!r}'
    return text.replace(before, after, 1)
def dump(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False) + '\n'

# Keep every previously committed artwork byte for byte, across all face sets.
tracked = subprocess.check_output(['git','ls-files','web/public/tiles','docs/design'], text=True).splitlines()
old_art = {p: sha(Path(p).read_bytes()) for p in tracked if Path(p).suffix in ['.svg','.png','.webp']}
manifest_path = 'web/public/tiles/dali/manifest.json'
manifest = json.loads(read(manifest_path))
old_entries = json.loads(json.dumps(manifest['tiles']))
assert len(old_entries) == 19 and len(manifest['placeholders']) == 15
assert all(entry['tile'] != '6s' for entry in old_entries)
assert sum(entry['tile'] == '6s' for entry in manifest['placeholders']) == 1

payload = ''.join(read(f'.github/dali-six-payload/{i}.b64') for i in range(4))
raster = base64.b64decode(payload, validate=True)
assert len(raster) == 42892 and sha(raster) == RASTER
metadata = {
    'tile':'6s', 'selectedOption':'C (third), green-hued revision',
    'originalFilename':'emerald_oasis_in_a_surreal_landscape.png', 'originalSha256':ORIGINAL,
    'originalDimensions':[1086,1448], 'originalStoredInRepository':False,
    'rasterDimensions':[450,600], 'rasterMimeType':'image/webp', 'rasterSha256':RASTER,
    'processing':'Complete approved green-hued third portrait resized with Lanczos to 450 x 600 and encoded as WebP quality 80, method 6. No crop, redraw, added tile background, border or further colour changes.'
}
svg = '<svg xmlns="http://www.w3.org/2000/svg" width="300" height="400" viewBox="0 0 300 400" role="img" aria-labelledby="title"><title id="title">6 bamboo — Dali — The Impossible Reflection — Green C</title><metadata>' + json.dumps(metadata,separators=(',',':'),ensure_ascii=False) + '</metadata><defs><clipPath id="face"><rect width="300" height="400" rx="26"/></clipPath></defs><image clip-path="url(#face)" x="-3" y="-4" width="306" height="408" preserveAspectRatio="none" href="data:image/webp;base64,' + payload + '"/></svg>\n'
assert sha(svg.encode()) == SVG_HASH
write(ART, svg)
write(RUNTIME, svg)
provenance = {'tile':'6s','name':'Sou6','status':'approved','direction':DIRECTION,'source':ART,'runtime':RUNTIME, **metadata,'svgSha256':SVG_HASH}
write('docs/design/dali/six-bamboo.json',dump(provenance))
entry = {'name':'Sou6','tile':'6s','label':'6 bamboo','direction':DIRECTION,'status':'approved','svg':'approved/Sou6.svg','source':ART,'sourceSha256':SVG_HASH,'svgSha256':SVG_HASH,'crop':{'x':0,'y':0,'width':450,'height':600}}
index = next(i for i,e in enumerate(manifest['tiles']) if e['tile']=='7s')
manifest['tiles'].insert(index,entry)
manifest['placeholders'] = [e for e in manifest['placeholders'] if e['tile']!='6s']
write(manifest_path,dump(manifest))
approved = [e['tile'] for e in manifest['tiles']]
assert len(approved)==20 and len(manifest['placeholders'])==14
assert [e for e in manifest['tiles'] if e['tile']!='6s']==old_entries
write('web/src/lib/dali-faces.js','// Generated by web/scripts/export-dali-tiles.mjs.\nexport const DALI_APPROVED = Object.freeze('+json.dumps(approved,separators=(',',':'))+');\n')

intro = 'Six bamboo uses C — The Impossible Reflection: the approved green-hued revision with six distinct bamboo stalks around a pool containing an impossible mountain landscape. The bamboo suit is complete. '
path = 'web/scripts/export-dali-tiles.mjs'
exporter = read(path)
exporter = replace_once(exporter,"  ['Sou7',", "  ['Sou6', '6s', '6 bamboo', 'The Impossible Reflection — Green C', 'six-bamboo-c-green-approved.svg', [0, 0, 450, 600]],\n  ['Sou7',")
exporter = replace_once(exporter,"'Sou2', 'Sou5', 'Man5'", "'Sou2', 'Sou6', 'Man5'")
exporter = replace_once(exporter,'${manifest.tiles.length} approved faces. ', '${manifest.tiles.length} approved faces. '+intro)
write(path,exporter)
# Reuse the exporter's own presentation templates without re-encoding older art.
subprocess.run(['node','--input-type=module','-e', "import {readFileSync,writeFileSync} from 'node:fs'; import path from 'node:path'; const manifest=JSON.parse(readFileSync('web/public/tiles/dali/manifest.json','utf8')); const out=path.resolve('web/public/tiles/dali'); const source=readFileSync('web/scripts/export-dali-tiles.mjs','utf8'); const start=source.indexOf('const cards ='); if(start<0) throw new Error('Missing preview template'); new Function('manifest','out','writeFileSync','path',source.slice(start))(manifest,out,writeFileSync,path);"],check=True)

# Update only the Dali coverage assertions; retain every existing artwork pin.
for path in ['web/tests/dali-bamboo.test.js','web/tests/dali-east-wind.test.js','web/tests/dali-north-wind.test.js']:
    text = read(path)
    assert 'set.tiles.length, 19' in text and 'set.placeholders.length, 15' in text
    text=text.replace('set.tiles.length, 19','set.tiles.length, 20').replace('set.placeholders.length, 15','set.placeholders.length, 14')
    text=text.replace('19 approved faces','20 approved faces').replace('remaining 15 tiles','remaining 14 tiles')
    if path.endswith('dali-bamboo.test.js'):
        text=replace_once(text,'nineteen approved identities and fifteen placeholders','twenty approved identities and fourteen placeholders')
        text=replace_once(text,"'4s', '5s', '7s'","'4s', '5s', '6s', '7s'")
        text=replace_once(text,"  for (const tile of ['6s']) {\n    assert.equal(tileImage(tile, 'dali'), 'tiles/dali/placeholders/placeholder.svg');\n  }", "  assert.equal(tileImage('6s', 'dali'), 'tiles/dali/approved/Sou6.svg');")
    write(path,text)
path='web/tests/tile-faces.test.js'
text=read(path)
start=text.index("test('Dali resolves")
end=text.index("test('hidden tiles",start)
block=text[start:end]
block=replace_once(block,'nineteen approved images','twenty approved images')
block=replace_once(block,"'4s', '5s', '7s'","'4s', '5s', '6s', '7s'")
block=replace_once(block,"['3s', '4s', '7s'","['3s', '4s', '6s', '7s'")
block=replace_once(block,"  assert.equal(tileImage('7s', 'dali')", "  assert.equal(tileImage('6s', 'dali'), 'tiles/dali/approved/Sou6.svg');\n  assert.equal(tileImage('7s', 'dali')")
write(path,text[:start]+block+text[end:])

path='docs/design/dali/README.md'
text=read(path)
text=replace_once(text,'Nineteen faces are approved','Twenty faces are approved')
text=replace_once(text,'The latest is four bamboo', 'The latest is six bamboo **The Impossible Reflection — Green C**, the selected third option with its approved green hue. This completes all nine bamboo faces. The previously selected four bamboo')
text=replace_once(text,'**The Sleeping Landscape — B**, using the approved', '**The Sleeping Landscape — B** uses the approved')
text=replace_once(text,'| `Sou7.svg` |','| `Sou6.svg` | 6 bamboo | The Impossible Reflection — Green C: six green stalks surround a pool containing a different mountain landscape |\n| `Sou7.svg` |')
text=replace_once(text,'The other 15 faces','The other 14 faces')
text=replace_once(text,'Six bamboo is the only remaining bamboo placeholder; three uses selected A and four uses the approved B adaptation.','All nine bamboo faces are now approved; six uses the selected green-hued C, three uses selected A and four uses the approved B adaptation.')
text=replace_once(text,'nineteen approved faces plus one shared placeholder','twenty approved faces plus one shared placeholder')
paragraph = '\nSix bamboo uses [the selected third option with its approved green hue](studies/six-bamboo-c-green-approved.svg), **The Impossible Reflection — Green C**. Six clearly separated stalks surround a pool containing an impossible mountain landscape. The source is `emerald_oasis_in_a_surreal_landscape.png` (1086 × 1448; SHA-256 `'+ORIGINAL+'`), not the original warmer C, floating-roots A or folded-landscape B. The complete portrait is resized proportionally with Lanczos to a 450 × 600 WebP at quality 80, method 6; no additional crop, redraw, recolouring, tile background or decorative frame is added. The SVG retains the existing 300 × 400 logical canvas, rounded clipping and bleed. Source and runtime SVGs are byte-identical. The original PNG remains in the conversation, while the repository stores the optimized rendering and [provenance](six-bamboo.json), not those original PNG bytes. All nineteen previously approved faces and all other sets remain unchanged.\n'
text=replace_once(text,'\nSeven bamboo uses ',paragraph+'\nSeven bamboo uses ')
write(path,text)

for path,digest in old_art.items():
    assert sha(Path(path).read_bytes())==digest, f'Changed older artwork: {path}'
assert Path(ART).read_bytes()==Path(RUNTIME).read_bytes()
print(f'Prepared 6s. Preserved {len(old_art)} earlier artwork files byte for byte. 20 approved / 14 placeholders.')
