// Generated by web/scripts/export-matisse-tiles.mjs.
export const MATISSE_APPROVED = Object.freeze(["1p","2p","3p","4p","5p","6p","7p","9p","2s","3s","4s","5s","6s","7s","8s","9s","1z","2z","3z","4z","7z","1m","2m","3m","5m","6m","7m","9m","1s","6z","5z"]);
