async function ortWasmThreaded(moduleArg={}){var moduleRtn;var f=moduleArg,aa=!!globalThis.window,g=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,m=g&&self.name?.startsWith("em-pthread");if(l){const {createRequire:a}=await import("module");var require=a(import.meta.url),n=require("worker_threads");global.Worker=n.Worker;m=(g=!n.jb)&&"em-pthread"==n.workerData}f.mountExternalData=(a,b)=>{a.startsWith("./")&&(a=a.substring(2));(f.Ta||(f.Ta=new Map)).set(a,b)};
f.unmountExternalData=()=>{delete f.Ta;delete f.mb;delete f.lb;delete f.nb};var SharedArrayBuffer=globalThis.SharedArrayBuffer??(new WebAssembly.Memory({initial:0,maximum:0,shared:!0})).buffer.constructor,ba="./this.program",p=(a,b)=>{throw b;},ca=import.meta.url,r="",da,t;
if(l){var fs=require("fs");ca.startsWith("file:")&&(r=require("path").dirname(require("url").fileURLToPath(ca))+"/");t=a=>{a=u(a)?new URL(a):a;return fs.readFileSync(a)};da=async a=>{a=u(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);p=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||g){try{r=(new URL(".",ca)).href}catch{}l||(g&&(t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),da=async a=>{if(u(a))return new Promise((d,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?d(e.response):c(e.status)};e.onerror=c;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);})}var ea=console.log.bind(console),fa=console.error.bind(console);
if(l){var ha=require("util"),ia=a=>"object"==typeof a?ha.inspect(a):a;ea=(...a)=>fs.writeSync(1,a.map(ia).join(" ")+"\n");fa=(...a)=>fs.writeSync(2,a.map(ia).join(" ")+"\n")}var ja=ea,v=fa,w,x,y=!1,z,u=a=>a.startsWith("file://");function A(){B.buffer!=C.buffer&&D()}var ka,la;
if(l&&m){var ma=n.parentPort;ma.on("message",a=>global.onmessage?.({data:a}));Object.assign(globalThis,{self:global,postMessage:a=>ma.postMessage(a)});process.on("uncaughtException",a=>{postMessage({Sa:"uncaughtException",error:a});process.exit(1)})}var na;
if(m){var oa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var d=b.data,c=d.Sa;if("load"===c){let e=[];self.onmessage=h=>e.push(h);na=()=>{postMessage({Sa:"loaded"});for(let h of e)a(h);self.onmessage=a};for(const h of d.ab)if(!f[h]||f[h].proxy)f[h]=(...k)=>{postMessage({Sa:"callHandler",$a:h,args:k})},"print"==h&&(ja=f[h]),"printErr"==h&&(v=f[h]);B=d.gb;D();x=d.hb;pa();E()}else if("run"===c){qa(d.Ra);ra(d.Ra,0,0,1,0,0);sa();ta(d.Ra);oa||=!0;try{ua(d.eb,d.Wa)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==d.target&&("checkMailbox"===c?oa&&G():c&&(v(`worker: received unknown command ${c}`),v(d)))}catch(e){throw va(),e;}}self.onmessage=a}var C,H,wa,I,J,xa,K,L,Aa=!1;function D(){var a=B.buffer;f.HEAP8=C=new Int8Array(a);wa=new Int16Array(a);f.HEAPU8=H=new Uint8Array(a);new Uint16Array(a);f.HEAP32=I=new Int32Array(a);f.HEAPU32=J=new Uint32Array(a);xa=new Float32Array(a);K=new Float64Array(a);L=new BigInt64Array(a);new BigUint64Array(a)}
function Ba(){Aa=!0;m?na():M.aa()}function N(a){a="Aborted("+a+")";v(a);y=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");la?.(a);throw a;}var Ca;async function Da(a){if(!w)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==Ca&&w)a=new Uint8Array(w);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ea(a,b){try{var d=await Da(a);return await WebAssembly.instantiate(d,b)}catch(c){v(`failed to asynchronously prepare wasm: ${c}`),N(c)}}async function Fa(a){var b=Ca;if(!w&&!u(b)&&!l)try{var d=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(c){v(`wasm streaming compile failed: ${c}`),v("falling back to ArrayBuffer instantiation")}return Ea(b,a)}
function Ga(){Ha={E:Ia,b:Ja,D:Ka,e:La,V:Ma,z:Na,B:Oa,W:Pa,T:Qa,M:Ra,S:Sa,m:Ta,A:Ua,x:Va,U:Wa,y:Xa,$:Ya,P:Za,v:$a,F:ab,r:bb,g:cb,O:ta,Y:db,J:eb,K:fb,L:gb,H:hb,I:ib,s:jb,o:kb,_:lb,l:mb,h:nb,Z:ob,i:pb,X:qb,w:rb,c:sb,f:tb,u:O,t:ub,q:vb,p:wb,Q:xb,R:yb,C:zb,d:Ab,G:Bb,k:Cb,N:Db,j:Eb,a:B,n:Fb};return{a:Ha}}
async function pa(){function a(c,e){M=c.exports;M=Gb();Hb.push(M.Ea);c=M;f._OrtInit=c.ba;f._OrtGetLastError=c.ca;f._OrtCreateSessionOptions=c.da;f._OrtAppendExecutionProvider=c.ea;f._OrtAddFreeDimensionOverride=c.fa;f._OrtAddSessionConfigEntry=c.ga;f._OrtReleaseSessionOptions=c.ha;f._OrtCreateSession=c.ia;f._OrtReleaseSession=c.ja;f._OrtGetInputOutputCount=c.ka;f._OrtGetInputOutputMetadata=c.la;f._OrtFree=c.ma;f._OrtCreateTensor=c.na;f._OrtGetTensorData=c.oa;f._OrtReleaseTensor=c.pa;f._OrtCreateRunOptions=
c.qa;f._OrtAddRunConfigEntry=c.ra;f._OrtReleaseRunOptions=c.sa;f._OrtCreateBinding=c.ta;f._OrtBindInput=c.ua;f._OrtBindOutput=c.va;f._OrtClearBoundOutputs=c.wa;f._OrtReleaseBinding=c.xa;f._OrtRunWithBinding=c.ya;f._OrtRun=c.za;f._OrtEndProfiling=c.Aa;P=c.Ba;Ib=f._free=c.Ca;Jb=f._malloc=c.Da;ra=c.Ga;va=c.Ha;Kb=c.Ia;Lb=c.Ja;Mb=c.Ka;Nb=c.La;Pb=c.Ma;Qb=c.Na;Rb=c.Oa;Sb=c.Pa;Tb=c.Qa;Ub=c.Fa;x=e;return M}var b=Ga();if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(e,h)=>{c(a(e,h))})});if(m){var d=
new WebAssembly.Instance(x,Ga());return a(d,x)}Ca??=f.locateFile?f.locateFile?f.locateFile("ort-wasm-simd-threaded.wasm",r):r+"ort-wasm-simd-threaded.wasm":(new URL("ort-wasm-simd-threaded.wasm",import.meta.url)).href;return function(c){return a(c.instance,c.module)}(await Fa(b))}class Vb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Wb=a=>{a.terminate();a.onmessage=()=>{}},Xb=[],Q=0,R=null,$b=a=>{0==S.length&&(Yb(),Zb(S[0]));var b=S.pop();if(!b)return 6;T.push(b);U[a.Ra]=b;b.Ra=a.Ra;var d={Sa:"run",eb:a.cb,Wa:a.Wa,Ra:a.Ra};l&&b.unref();b.postMessage(d,a.Za);return 0},V=0,W=(a,b,...d)=>{var c=16*d.length,e=Tb(),h=Sb(c),k=h>>>3,q;for(q of d)"bigint"==typeof q?((A(),L)[k++>>>0]=1n,(A(),L)[k++>>>0]=q):((A(),L)[k++>>>0]=0n,(A(),K)[k++>>>0]=q);a=Kb(a,0,c,h,b);Rb(e);return a};
function Fb(a){if(m)return W(0,1,a);z=a;if(!(0<V)){for(var b of T)Wb(b);for(b of S)Wb(b);S=[];T=[];U={};y=!0}p(a,new Vb(a))}function ac(a){if(m)return W(1,0,a);zb(a)}var zb=a=>{z=a;if(m)throw ac(a),"unwind";Fb(a)},S=[],T=[],Hb=[],U={};function bc(){for(var a=f.numThreads-1;a--;)Yb();Xb.push(async()=>{var b=cc();Q++;await b;Q--;0==Q&&R&&(b=R,R=null,b())})}var dc=a=>{var b=a.Ra;delete U[b];S.push(a);T.splice(T.indexOf(a),1);a.Ra=0;Lb(b)};function sa(){Hb.forEach(a=>a())}
var Zb=a=>new Promise(b=>{a.onmessage=h=>{var k=h.data;h=k.Sa;if(k.Ua&&k.Ua!=P()){var q=U[k.Ua];q?q.postMessage(k,k.Za):v(`Internal error! Worker sent a message "${h}" to target pthread ${k.Ua}, but that thread no longer exists!`)}else if("checkMailbox"===h)G();else if("spawnThread"===h)$b(k);else if("cleanupThread"===h)ec(()=>{dc(U[k.fb])});else if("loaded"===h)a.loaded=!0,l&&!a.Ra&&a.unref(),b(a);else if("setimmediate"===k.target)a.postMessage(k);else if("uncaughtException"===h)a.onerror(k.error);
else if("callHandler"===h)f[k.$a](...k.args);else h&&v(`worker sent an unknown command ${h}`)};a.onerror=h=>{v(`${"worker sent an error!"} ${h.filename}:${h.lineno}: ${h.message}`);throw h;};l&&(a.on("message",h=>a.onmessage({data:h})),a.on("error",h=>a.onerror(h)));var d=[],c=[],e;for(e of c)f.propertyIsEnumerable(e)&&d.push(e);a.postMessage({Sa:"load",ab:d,gb:B,hb:x})});async function cc(){if(!m)return Promise.all(S.map(Zb))}
function Yb(){var a=new Worker(new URL(import.meta.url),{type:"module",workerData:"em-pthread",name:"em-pthread"});S.push(a)}function qa(a){var b=(A(),J)[a+52>>>2>>>0];a=(A(),J)[a+56>>>2>>>0];Qb(b,b-a);Rb(b)}var ua=(a,b)=>{V=0;a=Ub.get(a)(b);0<V?z=a:Mb(a)},B;class fc{constructor(a){this.Va=a-24}}var gc=0,hc=0;
function Ja(a,b,d){a>>>=0;var c=new fc(a);b>>>=0;d>>>=0;(A(),J)[c.Va+16>>>2>>>0]=0;(A(),J)[c.Va+4>>>2>>>0]=b;(A(),J)[c.Va+8>>>2>>>0]=d;gc=a;hc++;throw gc;}function ic(a,b,d,c){return m?W(2,1,a,b,d,c):Ka(a,b,d,c)}function Ka(a,b,d,c){a>>>=0;b>>>=0;d>>>=0;c>>>=0;if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(m&&0===e.length)return ic(a,b,d,c);a={cb:d,Ra:a,Wa:c,Za:e};return m?(a.Sa="spawnThread",postMessage(a,e),0):$b(a)}
var jc=globalThis.TextDecoder&&new TextDecoder,kc=(a,b=0,d,c)=>{b>>>=0;var e=b;d=e+d;if(c)c=d;else{for(;a[e]&&!(e>=d);)++e;c=e}if(16<c-b&&a.buffer&&jc)return jc.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(e="";b<c;)if(d=a[b++],d&128){var h=a[b++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|h);else{var k=a[b++]&63;d=224==(d&240)?(d&15)<<12|h<<6|k:(d&7)<<18|h<<12|k<<6|a[b++]&63;65536>d?e+=String.fromCharCode(d):(d-=65536,e+=String.fromCharCode(55296|d>>10,56320|
d&1023))}}else e+=String.fromCharCode(d);return e},lc=(a,b,d)=>(a>>>=0)?kc((A(),H),a,b,d):"";function La(a,b,d){return m?W(3,1,a,b,d):0}function Ma(a,b){if(m)return W(4,1,a,b)}function Na(a,b){if(m)return W(5,1,a,b)}function Oa(a,b,d){if(m)return W(6,1,a,b,d)}function Pa(a,b,d){return m?W(7,1,a,b,d):0}function Qa(a,b){if(m)return W(8,1,a,b)}function Ra(a,b,d){if(m)return W(9,1,a,b,d)}function Sa(a,b,d,c){if(m)return W(10,1,a,b,d,c)}function Ta(a,b,d,c){if(m)return W(11,1,a,b,d,c)}
function Ua(a,b,d,c){if(m)return W(12,1,a,b,d,c)}function Va(a){if(m)return W(13,1,a)}function Wa(a,b){if(m)return W(14,1,a,b)}function Xa(a,b,d){if(m)return W(15,1,a,b,d)}var Ya=()=>N("");function Za(a){ra(a>>>0,!g,1,!aa,131072,!1);sa()}
var ec=a=>{if(!y)try{if(a(),!(0<V))try{m?P()&&Mb(z):zb(z)}catch(b){b instanceof Vb||"unwind"==b||p(1,b)}}catch(b){b instanceof Vb||"unwind"==b||p(1,b)}},mc=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]);function ta(a){a>>>=0;mc||(Atomics.waitAsync((A(),I),a>>>2,a).value.then(G),a+=128,Atomics.store((A(),I),a>>>2,1))}var G=()=>ec(()=>{var a=P();a&&(ta(a),Pb())});
function $a(a,b){a>>>=0;a==b>>>0?setTimeout(G):m?postMessage({Ua:a,Sa:"checkMailbox"}):(a=U[a])&&a.postMessage({Sa:"checkMailbox"})}var nc=[];function ab(a,b,d,c,e){b>>>=0;e>>>=0;nc.length=0;d=e>>>3;for(c=e+c>>>3;d<c;){var h;(A(),L)[d++>>>0]?h=(A(),L)[d++>>>0]:h=(A(),K)[d++>>>0];nc.push(h)}return(b?oc[b]:pc[a])(...nc)}var bb=()=>{V=0};function cb(a){a>>>=0;m?postMessage({Sa:"cleanupThread",fb:a}):dc(U[a])}function db(a){l&&U[a>>>0].ref()}
function eb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);(A(),I)[b>>>2>>>0]=a.getUTCSeconds();(A(),I)[b+4>>>2>>>0]=a.getUTCMinutes();(A(),I)[b+8>>>2>>>0]=a.getUTCHours();(A(),I)[b+12>>>2>>>0]=a.getUTCDate();(A(),I)[b+16>>>2>>>0]=a.getUTCMonth();(A(),I)[b+20>>>2>>>0]=a.getUTCFullYear()-1900;(A(),I)[b+24>>>2>>>0]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;(A(),I)[b+28>>>2>>>0]=a}
var qc=a=>0===a%4&&(0!==a%100||0===a%400),rc=[0,31,60,91,121,152,182,213,244,274,305,335],sc=[0,31,59,90,120,151,181,212,243,273,304,334];
function fb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);(A(),I)[b>>>2>>>0]=a.getSeconds();(A(),I)[b+4>>>2>>>0]=a.getMinutes();(A(),I)[b+8>>>2>>>0]=a.getHours();(A(),I)[b+12>>>2>>>0]=a.getDate();(A(),I)[b+16>>>2>>>0]=a.getMonth();(A(),I)[b+20>>>2>>>0]=a.getFullYear()-1900;(A(),I)[b+24>>>2>>>0]=a.getDay();var d=(qc(a.getFullYear())?rc:sc)[a.getMonth()]+a.getDate()-1|0;(A(),I)[b+28>>>2>>>0]=d;(A(),I)[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();var c=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;(A(),I)[b+32>>>2>>>0]=a}
function gb(a){a>>>=0;var b=new Date((A(),I)[a+20>>>2>>>0]+1900,(A(),I)[a+16>>>2>>>0],(A(),I)[a+12>>>2>>>0],(A(),I)[a+8>>>2>>>0],(A(),I)[a+4>>>2>>>0],(A(),I)[a>>>2>>>0],0),d=(A(),I)[a+32>>>2>>>0],c=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),k=Math.min(h,e);0>d?(A(),I)[a+32>>>2>>>0]=Number(e!=h&&k==c):0<d!=(k==c)&&(e=Math.max(h,e),b.setTime(b.getTime()+6E4*((0<d?k:e)-c)));(A(),I)[a+24>>>2>>>0]=b.getDay();d=(qc(b.getFullYear())?
rc:sc)[b.getMonth()]+b.getDate()-1|0;(A(),I)[a+28>>>2>>>0]=d;(A(),I)[a>>>2>>>0]=b.getSeconds();(A(),I)[a+4>>>2>>>0]=b.getMinutes();(A(),I)[a+8>>>2>>>0]=b.getHours();(A(),I)[a+12>>>2>>>0]=b.getDate();(A(),I)[a+16>>>2>>>0]=b.getMonth();(A(),I)[a+20>>>2>>>0]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)}function hb(a,b,d,c,e,h,k){return m?W(16,1,a,b,d,c,e,h,k):-52}function ib(a,b,d,c,e,h){if(m)return W(17,1,a,b,d,c,e,h)}var X={},sb=()=>performance.timeOrigin+performance.now();
function jb(a,b){if(m)return W(18,1,a,b);X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var d=setTimeout(()=>{delete X[a];ec(()=>Nb(a,performance.timeOrigin+performance.now()))},b);X[a]={id:d,ob:b};return 0}
var Y=(a,b,d)=>{var c=(A(),H);b>>>=0;if(0<d){var e=b;d=b+d-1;for(var h=0;h<a.length;++h){var k=a.codePointAt(h);if(127>=k){if(b>=d)break;c[b++>>>0]=k}else if(2047>=k){if(b+1>=d)break;c[b++>>>0]=192|k>>6;c[b++>>>0]=128|k&63}else if(65535>=k){if(b+2>=d)break;c[b++>>>0]=224|k>>12;c[b++>>>0]=128|k>>6&63;c[b++>>>0]=128|k&63}else{if(b+3>=d)break;c[b++>>>0]=240|k>>18;c[b++>>>0]=128|k>>12&63;c[b++>>>0]=128|k>>6&63;c[b++>>>0]=128|k&63;h++}}c[b>>>0]=0;a=b-e}else a=0;return a};
function kb(a,b,d,c){a>>>=0;b>>>=0;d>>>=0;c>>>=0;var e=(new Date).getFullYear(),h=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var k=Math.max(h,e);(A(),J)[a>>>2>>>0]=60*k;(A(),I)[b>>>2>>>0]=Number(h!=e);b=q=>{var F=Math.abs(q);return`UTC${0<=q?"-":"+"}${String(Math.floor(F/60)).padStart(2,"0")}${String(F%60).padStart(2,"0")}`};a=b(h);b=b(e);e<h?(Y(a,d,17),Y(b,c,17)):(Y(a,c,17),Y(b,d,17))}var ob=()=>Date.now(),tc=1;
function lb(a,b,d){d>>>=0;if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(tc)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(A(),L)[d>>>3>>>0]=BigInt(a);return 0}var uc=[];function mb(a,b,d){a>>>=0;b>>>=0;d>>>=0;uc.length=0;for(var c;c=(A(),H)[b++>>>0];){var e=105!=c;e&=112!=c;d+=e&&d%8?4:0;uc.push(112==c?(A(),J)[d>>>2>>>0]:106==c?(A(),L)[d>>>3>>>0]:105==c?(A(),I)[d>>>2>>>0]:(A(),K)[d>>>3>>>0]);d+=e?8:4}return oc[a](...uc)}var nb=()=>{};
function pb(a,b){return v(lc(a>>>0,b>>>0))}var qb=()=>{V+=1;throw"unwind";};function rb(){return 4294901760}var tb=()=>l?require("os").cpus().length:navigator.hardwareConcurrency,Z={},vc=a=>{for(var b=0,d=0;d<a.length;++d){var c=a.charCodeAt(d);127>=c?b++:2047>=c?b+=2:55296<=c&&57343>=c?(b+=4,++d):b+=3}return b},wc=a=>{var b;return(b=/\bwasm-function\[\d+\]:(0x[0-9a-f]+)/.exec(a))?+b[1]:(b=/:(\d+):\d+(?:\)|$)/.exec(a))?2147483648|+b[1]:0},xc=a=>{for(var b of a)(a=wc(b))&&(Z[a]=b)};
function vb(){var a=Error().stack.toString().split("\n");"Error"==a[0]&&a.shift();xc(a);Z.Xa=wc(a[3]);Z.bb=a;return Z.Xa}function O(a){a=Z[a>>>0];if(!a)return 0;var b;if(b=/^\s+at .*\.wasm\.(.*) \(.*\)$/.exec(a))a=b[1];else if(b=/^\s+at (.*) \(.*\)$/.exec(a))a=b[1];else if(b=/^(.+?)@/.exec(a))a=b[1];else return 0;Ib(O.Ya??0);b=vc(a)+1;var d=Jb(b);d&&Y(a,d,b);O.Ya=d;return O.Ya}
function ub(a){a>>>=0;var b=(A(),H).length;if(a<=b||4294901760<a)return!1;for(var d=1;4>=d;d*=2){var c=b*(1+.2/d);c=Math.min(c,a+100663296);a:{c=(Math.min(4294901760,65536*Math.ceil(Math.max(a,c)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(c);D();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1}
function wb(a,b,d){a>>>=0;b>>>=0;if(Z.Xa==a)var c=Z.bb;else c=Error().stack.toString().split("\n"),"Error"==c[0]&&c.shift(),xc(c);for(var e=3;c[e]&&wc(c[e])!=a;)++e;for(a=0;a<d&&c[a+e];++a)(A(),I)[b+4*a>>>2>>>0]=wc(c[a+e]);return a}
var yc={},Ac=()=>{if(!zc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in yc)void 0===yc[b]?delete a[b]:a[b]=yc[b];var d=[];for(b in a)d.push(`${b}=${a[b]}`);zc=d}return zc},zc;function xb(a,b){if(m)return W(19,1,a,b);a>>>=0;b>>>=0;var d=0,c=0,e;for(e of Ac()){var h=b+d;(A(),J)[a+c>>>2>>>0]=h;d+=Y(e,h,Infinity)+1;c+=4}return 0}
function yb(a,b){if(m)return W(20,1,a,b);a>>>=0;b>>>=0;var d=Ac();(A(),J)[a>>>2>>>0]=d.length;a=0;for(var c of d)a+=vc(c)+1;(A(),J)[b>>>2>>>0]=a;return 0}function Ab(a){return m?W(21,1,a):52}function Bb(a,b,d,c,e){return m?W(22,1,a,b,d,c,e):52}function Cb(a,b,d,c){return m?W(23,1,a,b,d,c):52}function Db(a,b,d,c){return m?W(24,1,a,b,d,c):70}var Bc=[null,[],[]];
function Eb(a,b,d,c){if(m)return W(25,1,a,b,d,c);b>>>=0;d>>>=0;c>>>=0;for(var e=0,h=0;h<d;h++){var k=(A(),J)[b>>>2>>>0],q=(A(),J)[b+4>>>2>>>0];b+=8;for(var F=0;F<q;F++){var Ob=a,ya=(A(),H)[k+F>>>0],za=Bc[Ob];0===ya||10===ya?((1===Ob?ja:v)(kc(za)),za.length=0):za.push(ya)}e+=q}(A(),J)[c>>>2>>>0]=e;return 0}m||bc();m||(B=new WebAssembly.Memory({initial:256,maximum:65536,shared:!0}),D());f.wasmBinary&&(w=f.wasmBinary);f.stackSave=()=>Tb();f.stackRestore=a=>Rb(a);f.stackAlloc=a=>Sb(a);
f.setValue=function(a,b,d="i8"){d.endsWith("*")&&(d="*");switch(d){case "i1":(A(),C)[a>>>0]=b;break;case "i8":(A(),C)[a>>>0]=b;break;case "i16":(A(),wa)[a>>>1>>>0]=b;break;case "i32":(A(),I)[a>>>2>>>0]=b;break;case "i64":(A(),L)[a>>>3>>>0]=BigInt(b);break;case "float":(A(),xa)[a>>>2>>>0]=b;break;case "double":(A(),K)[a>>>3>>>0]=b;break;case "*":(A(),J)[a>>>2>>>0]=b;break;default:N(`invalid type for setValue: ${d}`)}};
f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return(A(),C)[a>>>0];case "i8":return(A(),C)[a>>>0];case "i16":return(A(),wa)[a>>>1>>>0];case "i32":return(A(),I)[a>>>2>>>0];case "i64":return(A(),L)[a>>>3>>>0];case "float":return(A(),xa)[a>>>2>>>0];case "double":return(A(),K)[a>>>3>>>0];case "*":return(A(),J)[a>>>2>>>0];default:N(`invalid type for getValue: ${b}`)}};f.UTF8ToString=lc;f.stringToUTF8=Y;f.lengthBytesUTF8=vc;
var pc=[Fb,ac,ic,La,Ma,Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,hb,ib,jb,xb,yb,Ab,Bb,Cb,Db,Eb],oc={536204:(a,b,d,c,e)=>{if("undefined"==typeof f||!f.Ta)return 1;a=lc(Number(a>>>0));a.startsWith("./")&&(a=a.substring(2));a=f.Ta.get(a);if(!a)return 2;b=Number(b>>>0);d=Number(d>>>0);c=Number(c>>>0);if(b+d>a.byteLength)return 3;try{const h=a.subarray(b,b+d);switch(e){case 0:(A(),H).set(h,c>>>0);break;case 1:f.ib?f.ib(c,h):f.kb(c,h);break;default:return 4}return 0}catch{return 4}},537028:()=>"undefined"!==typeof wasmOffsetConverter};
function Ia(){return"undefined"!==typeof wasmOffsetConverter}var P,Ib,Jb,ra,va,Kb,Lb,Mb,Nb,Pb,Qb,Rb,Sb,Tb,Ub,Ha;function Gb(){var a=M;a=Object.assign({},a);var b=c=>()=>c()>>>0,d=c=>e=>c(e)>>>0;a.Ba=b(a.Ba);a.Da=d(a.Da);a.Pa=d(a.Pa);a.Qa=b(a.Qa);return a}function E(){if(0<Q)R=E;else if(m)ka?.(f),Ba();else{for(var a=Xb;0<a.length;)a.shift()(f);0<Q?R=E:(f.calledRun=!0,y||(Ba(),ka?.(f)))}}var M;m||(M=await (pa()),E());f.PTR_SIZE=4;Aa?moduleRtn=f:moduleRtn=new Promise((a,b)=>{ka=a;la=b});
;return moduleRtn}export default ortWasmThreaded;var isPthread=globalThis.self?.name?.startsWith("em-pthread");var isNode=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(isNode)isPthread=(await import("worker_threads")).workerData==="em-pthread";isPthread&&ortWasmThreaded();
