"""Reconcile approved Four Oranges A with current main, retaining Irises C and all other work."""
import base64
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess

STAGE = Path('.oranges-transfer')
SOURCE = 'docs/design/van-gogh/studies/20-four-disks-oranges-a-approved.svg'
RUNTIME = 'web/public/tiles/van-gogh/approved/Pin4.svg'
PROVENANCE = 'docs/design/van-gogh/four-disks-oranges.json'
EXPORTER = 'web/scripts/export-van-gogh-tiles.mjs'
MANIFEST = 'web/public/tiles/van-gogh/manifest.json'
NEW_TEST = 'web/tests/van-gogh-four-oranges.test.js'


def digest(data):
    return hashlib.sha256(data).hexdigest()


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise RuntimeError(f'Expected exactly one patch anchor: {old!r}')
    return text.replace(old, new, 1)


before = json.loads(Path(MANIFEST).read_text())
assert '4p' in before['remaining']
assert len(before['tiles']) == 24
assert any(t['tile'] == '7m' and t['candidate'] == 'Irises C' for t in before['tiles'])
assert not any(t['tile'] == '4p' for t in before['tiles'])
protected = {p: digest(p.read_bytes()) for p in Path('web/public/tiles').rglob('*') if p.is_file() and p.suffix in ('.svg', '.png', '.webp')}
for source in before['sources']:
    p = Path(source['source'])
    protected[p] = digest(p.read_bytes())
svg = (STAGE / 'approved.svg').read_bytes()
assert digest(svg) == '52d7428647df0da97da13594c0913a4849e723ed9ff5d921b5fe2b3b6944a4d1'
match = re.search(rb'href="data:image/webp;base64,([A-Za-z0-9+/=]+)"', svg)
assert match
raster = base64.b64decode(match[1], validate=True)
assert len(raster) == 66718
assert digest(raster) == 'e2dcad697285d2baa13e0b4f227b1e2f7016279f15252cd4aa5f53fe6922a9ba'
Path(SOURCE).write_bytes(svg)
shutil.copyfile(STAGE / 'provenance.json', PROVENANCE)
shutil.copyfile(STAGE / 'oranges.test.js', NEW_TEST)

s = Path(EXPORTER).read_text()
anchor = "  sevenCharactersIrises: 'docs/design/van-gogh/studies/20-seven-characters-irises-c-approved.svg',"
s = replace_once(s, anchor, anchor + f"\n  fourOranges: '{SOURCE}',")
anchor = "  ['Irises C', '7m', 'Seven characters', 'sevenCharactersIrises', [0, 0, 300, 400]],"
s = replace_once(s, anchor, anchor + "\n  ['Oranges A', '4p', 'Four disks', 'fourOranges', [0, 0, 300, 400]],")
lines = s.splitlines(keepends=True)
indices = [i for i, line in enumerate(lines) if line.startswith("  approval: '")]
assert len(indices) == 1
index = indices[0]
assert lines[index].endswith("',\n")
lines[index] = lines[index][:-3] + ' Carl selected A, Four Oranges, the left panel with four whole oranges on blue cloth, for 4 disks (4p / Pin4) and explicitly requested GitHub deployment. The complete approved crop is retained without repainting or recolouring; the bowl and orange-slice alternatives are not used.' + "',\n"
s = ''.join(lines)
anchor = '// Generated by web/scripts/export-van-gogh-tiles.mjs. Includes '
s = replace_once(s, anchor, anchor + 'Four Oranges A (4p), ')
s = replace_once(s, "const featured = ['7m', '6m', '5m', '2m', '3m', '4m', '9p', '3p', '9s', '6s', '8s', '7s'];", "const featured = ['4p', '7m', '6m', '5m', '2m', '3m', '4m', '9p', '3p', '9s', '6s', '8s'];")
s = replace_once(s, 'approved faces, including ', 'approved faces, including Four Oranges A for 4 disks, ')
Path(EXPORTER).write_text(s)
subprocess.run(['node', EXPORTER, '--only=4p'], check=True)
after = json.loads(Path(MANIFEST).read_text())
assert after['tiles'][:-1] == before['tiles']
assert after['sources'][:-1] == before['sources']
assert after['remaining'] == [t for t in before['remaining'] if t != '4p']
assert len(after['tiles']) == 25 and len(after['remaining']) == 9
assert Path(RUNTIME).read_bytes() == svg

p = Path('web/tests/tile-faces.test.js')
s = p.read_text()
s = replace_once(s, "'9s', '3p', '5m', '6m', '7m'];", "'9s', '3p', '5m', '6m', '7m', '4p'];")
s = replace_once(s, "'Lemon Terrace', 'Irises C']);", "'Lemon Terrace', 'Irises C', 'Oranges A']);")
s = replace_once(s, "'9s', '3p', '5m', '6m', '7m'])", "'9s', '3p', '5m', '6m', '7m', '4p'])")
p.write_text(s)

section = '''\n## Four Oranges A — 4 disks\n\nCarl selected **A**, the left panel with **four whole oranges on blue cloth**, for `4p` / `Pin4` and explicitly requested GitHub deployment. The blue-and-white jug, leafy branch, yellow wall, window and distant village are preserved. The bowl (B) and orange slices (C) are not used.\n\nThe source `docs/design/van-gogh/studies/20-four-disks-oranges-a-approved.svg` and playable `web/public/tiles/van-gogh/approved/Pin4.svg` are identical. They embed a quality-90 300 × 400 WebP of the complete approved crop `[25, 138, 442, 796]` from the 1448 × 1086 concept board, with the set's 26-unit corners and 1% bleed. The label and presentation gutters were excluded; nothing was repainted or recoloured. The complete tall crop is fitted to the common face, changing its aspect ratio. This is a game-sized export, not the full-resolution original.\n\nBoard, full-resolution crop, decoded crop pixels, raster and SVG checksums are recorded in `docs/design/van-gogh/four-disks-oranges.json`. The original board and lossless selected crop are preserved in `Van_Gogh_4_Disks_Oranges_A_Approved.zip`, supplied in chat.\n\nRun `node web/scripts/export-van-gogh-tiles.mjs --only=4p` to reproduce this tile, its registration, manifest and preview without rewriting any other tile artwork. The set now has **25 painted faces and 9 Classic fallbacks**. All 24 previously approved faces remain unchanged, including Irises at Dusk C for 7 characters and the restored Nine Stars I.\n'''
p = Path('docs/design/van-gogh/README.md')
s = p.read_text()
lines = s.splitlines(keepends=True)
indices = [i for i, line in enumerate(lines) if line.startswith('**Current set:**')]
assert len(indices) == 1
lines[indices[0]] = '**Current set:** 25 painted faces and 9 Classic fallbacks; all nine bamboo identities are covered. Four Oranges A is active for 4 disks, Irises at Dusk C for 7 characters, Lemon Terrace for 6 characters, The Red Vineyard for 5 characters, and the restored Nine Stars I for 9 disks. The history below retains earlier milestone counts.\n'
p.write_text(''.join(lines).rstrip() + '\n' + section)
p = Path('web/public/tiles/van-gogh/README.md')
s = p.read_text()
s = replace_once(s, 'The twenty-four approved faces', 'The twenty-five approved faces')
s = replace_once(s, 'plus **Irises at Dusk C**', 'plus **Four Oranges A** for 4 disks, **Irises at Dusk C**')
s = replace_once(s, 'The other 10 identities awaiting Van Gogh artwork', 'The other 9 identities awaiting Van Gogh artwork')
p.write_text(s.rstrip() + '\n' + section)

outputs = [Path(p) for p in (SOURCE, RUNTIME, MANIFEST, 'web/src/lib/van-gogh-faces.js', 'web/public/tiles/van-gogh/preview.html')]
first = {p: digest(p.read_bytes()) for p in outputs}
subprocess.run(['node', EXPORTER, '--only=4p'], check=True)
assert {p: digest(p.read_bytes()) for p in outputs} == first
for p, expected in protected.items():
    assert digest(p.read_bytes()) == expected, f'Existing artwork changed: {p}'
print(f'PRESERVED {len(protected)} existing artwork/source files byte-for-byte.')
print(f'REPRODUCIBLE: {len(after["tiles"])} approved; {len(after["remaining"])} remaining.')
